@startuml Co2TA // Carbon Tech Assist
allowmixing

!include Co2TA_frontend.wsd
!include Co2TA_ODB.wsd
!include Co2TA_backend.wsd

actor "User" as User
collections "GitHub" as GitHub

User --> WebApp : Prompt
note top of User : "生産者の情報"
User <-- WebApp : "作成した申請書"



@enduml
